### ISSUE TITLE
Create issues template

### ISSUE THREAD

**Issue by a-sahel** [cybohr/n8n#6]
## Description
As a `GitHub` user, I want to have `issue` template, so that I can create create themes, epics, stories and tasks quickly

## Tasks
* [ ] Create `Theme` template
* [ ] Create `Epic` template
* [ ] Create `Story` template
* [ ] Create `Task` template
